#!/usr/bin/env python3
"""
RVS In A Box — Interactive Setup
Generates .env, docker-compose.yml and Caddyfile for a complete Raven Shield server stack.
No building required — images are pulled from registry.rvsinabox.com.

DISCLAIMER: You MUST own a legitimate copy of the game to use this.
"""

import os
import sys

REGISTRY = "registry.rvsinabox.com"

GAME_MODES = {
    "1": ("Terrorist Hunt Co-op", "R6Game.R6TerroristHuntCoopGame"),
    "2": ("Hostage Rescue Co-op", "R6Game.R6HostageRescueCoopGame"),
    "3": ("Hostage Rescue Advanced", "R6Game.R6HostageRescueAdvGame"),
    "4": ("Team Deathmatch", "R6Game.R6TeamDeathMatchGame"),
    "5": ("Bomb", "R6Game.R6TeamBomb"),
    "6": ("Escort Pilot", "R6Game.R6EscortPilotGame"),
    "7": ("Deathmatch", "R6Game.R6DeathMatch"),
    "8": ("Lone Wolf", "R6Game.R6LoneWolfGame"),
}

AVAILABLE_MAPS = [
    "Airport", "Alpines", "Bank", "CityStreet_LG", "Garage",
    "Import_Export", "Island_Dawn", "MeatPacking", "Mountain_High",
    "Oil_Refinery", "Parade", "Peaks", "Penthouse", "Presidio",
    "Prison", "Shipyard", "Streets", "Training", "Warehouse",
]

DEFAULT_MAPS = "Training,Airport,Bank,CityStreet_LG,Warehouse,Prison"


def banner():
    print()
    print("=" * 60)
    print()
    print("  RVS In A Box — Raven Shield Server Setup")
    print()
    print("  A complete game server, dashboard, and fast")
    print("  download server in one command.")
    print()
    print("=" * 60)
    print()

owns_game = prompt_yn("DISCLAIMER: You MUST own a legitimate copy of\n  Raven Shield to use this. Do you own the game?", default="n")
if not owns_game:
    print("\n  Please purchase Raven Shield before using RVS In A Box.")
    print("  https://store.steampowered.com/app/19830/Tom_Clancys_Rainbow_Six_3_Gold/")
    print()
    sys.exit(0)

def prompt(label, default=None, required=False, secret=False):
    if default is not None:
        display = f"  {label} [{default}]: "
    elif required:
        display = f"  {label} (required): "
    else:
        display = f"  {label}: "

    while True:
        if secret:
            import getpass
            value = getpass.getpass(display)
        else:
            value = input(display).strip()

        if value:
            return value
        elif default is not None:
            return str(default)
        elif required:
            print("    This field is required.")
        else:
            return ""


def prompt_yn(label, default="y"):
    suffix = "[Y/n]" if default == "y" else "[y/N]"
    while True:
        value = input(f"  {label} {suffix}: ").strip().lower()
        if value == "":
            return default == "y"
        if value in ("y", "yes"):
            return True
        if value in ("n", "no"):
            return False
        print("    Please enter y or n.")


def prompt_choice(label, choices):
    print(f"\n  {label}")
    for key, (name, _) in choices.items():
        print(f"    {key}) {name}")
    print()
    while True:
        value = input("  Choose [1]: ").strip()
        if value == "":
            return choices["1"]
        if value in choices:
            return choices[value]
        print("    Invalid choice.")


def write_env(config):
    env_lines = [
        "# =============================================================================",
        "# RVS In A Box — Generated Configuration",
        "# Generated by setup.py — edit values here, then: docker compose up -d",
        "# =============================================================================",
        "",
        "# --- Server Identity ---",
        f"SERVER_NAME={config['server_name']}",
        f"MOTD={config['motd']}",
        f"SERVER_IDENT={config['server_ident']}",
        "",
        "# --- Passwords ---",
        f"ADMIN_PASSWORD={config['admin_password']}",
        f"N4ADMIN_PASSWORD={config['n4admin_password']}",
        "",
        "# --- Game Settings ---",
        f"GAME_MODE={config['game_mode_class']}",
        f"GAME_MODE_NAME={config['game_mode_name']}",
        f"MAX_PLAYERS={config['max_players']}",
        f"NB_TERRO={config['nb_terro']}",
        f"ROUND_TIME={config['round_time']}",
        f"BETWEEN_ROUND_TIME={config['between_round_time']}",
        f"BOMB_TIME={config['bomb_time']}",
        f"ROUNDS_PER_MATCH={config['rounds_per_match']}",
        f"DIFF_LEVEL={config['diff_level']}",
        f"FRIENDLY_FIRE={config['friendly_fire']}",
        f"FORCE_FIRST_PERSON={config['force_first_person']}",
        f"ROTATE_MAP={config['rotate_map']}",
        f"MAPS={config['maps']}",
        "",
        "# --- Network ---",
        f"PUBLIC_IP={config['public_ip']}",
        f"SERVER_BEACON_PORT={config['server_beacon_port']}",
        f"RVSDASH_PORT={config['rvsdash_port']}",
        f"REDIRECT_URL=http://{config['public_ip']}/",
        "",
        "# --- Site Branding ---",
        f"SITE_TITLE={config['site_title']}",
        f"SITE_HEADING={config['site_heading']}",
        "FOOTER_HTML=&copy; 2026 <a href=\"https://obsoletesuperstars.com\">geekstrada</a>. Uses N4Admin &amp; URLPost &copy; 2004 Neil Popplewell. Uses N4IDMod &copy; 2020 <a href=\"https://dateranoth.com\">Dateranoth</a>.",
        "",
        "# --- Internal (do not change) ---",
        "RVSDASH_SERVER_IP=rvs-server",
        f"RVSDASH_SERVER_PORT={config['server_beacon_port']}",
    ]

    env_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env")
    with open(env_path, "w") as f:
        f.write("\n".join(env_lines) + "\n")


def write_compose(config):
    lines = []
    lines.append("services:")
    lines.append("  ravenshield:")
    lines.append(f"    image: {REGISTRY}/rvs-server:latest")
    lines.append("    container_name: rvs-server")
    lines.append("    restart: unless-stopped")
    lines.append("    ports:")
    lines.append('      - "7777:7777/udp"')
    lines.append(f'      - "{config["server_beacon_port"]}:{config["server_beacon_port"]}/udp"')
    lines.append('      - "9777:9777/udp"')
    lines.append("    env_file:")
    lines.append("      " + chr(45) + chr(32) + ".env")
    lines.append("    volumes:")
    lines.append("      - redirect-files:/srv/redirect")
    lines.append("")
    lines.append("  rvsdash:")
    lines.append(f"    image: {REGISTRY}/rvs-dash:latest")
    lines.append("    container_name: rvs-dash")
    lines.append("    restart: unless-stopped")
    lines.append("    ports:")
    lines.append(f'      - "{config["rvsdash_port"]}:2003"')
    lines.append("    volumes:")
    lines.append("      - rvsdash-data:/app/app/data")
    lines.append("    env_file:")
    lines.append("      " + chr(45) + chr(32) + ".env")
    lines.append("    environment:")
    lines.append("      - RVS_ADMIN_PASSWORD=${N4ADMIN_PASSWORD}")
    lines.append("      - DEFAULT_SERVER_IP=rvs-server")
    lines.append("      - DEFAULT_SERVER_PORT=${SERVER_BEACON_PORT:-8777}")
    lines.append("      - DEFAULT_SERVER_IDENT=${SERVER_IDENT:-rvs1}")
    lines.append("      - SITE_TITLE=${SITE_TITLE}")
    lines.append("      - SITE_HEADING=${SITE_HEADING}")
    lines.append("      - FOOTER_HTML=${FOOTER_HTML}")
    lines.append("    depends_on:")
    lines.append("      - ravenshield")
    lines.append("")
    lines.append("  redirect:")
    lines.append("    image: caddy:2-alpine")
    lines.append("    container_name: rvs-redirect")
    lines.append("    restart: unless-stopped")
    lines.append("    ports:")
    lines.append('      - "80:80"')
    lines.append("    volumes:")
    lines.append("      - redirect-files:/srv")
    lines.append("      " + chr(45) + chr(32) + "./Caddyfile:/etc/caddy/Caddyfile")
    lines.append("    depends_on:")
    lines.append("      - ravenshield")
    lines.append("")
    lines.append("volumes:")
    lines.append("  rvsdash-data:")
    lines.append("  redirect-files:")
    lines.append("")

    compose_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "docker-compose.yml")
    with open(compose_path, "w") as f:
        f.write("\n".join(lines))
def write_caddyfile():
    caddyfile = ":80 {\\n\\troot * /srv\\n\\tfile_server\\n}\\n"
    caddy_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "Caddyfile")
    with open(caddy_path, "w") as f:
        f.write(":80 {\n\troot * /srv\n\tfile_server\n}\n")


def main():
    banner()

    print("  --- Server Identity ---\n")
    server_name = prompt("Server Name", default="Raven Shield Server")
    motd = prompt("Message of the Day", default="Welcome! Have fun and play fair.")

    print("\n  --- Passwords ---\n")
    admin_password = prompt("Admin Password", required=True, secret=True)
    admin_password_confirm = prompt("Confirm Admin Password", required=True, secret=True)
    while admin_password != admin_password_confirm:
        print("    Passwords do not match. Try again.")
        admin_password = prompt("Admin Password", required=True, secret=True)
        admin_password_confirm = prompt("Confirm Admin Password", required=True, secret=True)

    use_separate_n4admin = prompt_yn("Use a separate password for RVSDash/N4Admin?", default="n")
    if use_separate_n4admin:
        n4admin_password = prompt("N4Admin Password", required=True, secret=True)
        n4admin_password_confirm = prompt("Confirm N4Admin Password", required=True, secret=True)
        while n4admin_password != n4admin_password_confirm:
            print("    Passwords do not match. Try again.")
            n4admin_password = prompt("N4Admin Password", required=True, secret=True)
            n4admin_password_confirm = prompt("Confirm N4Admin Password", required=True, secret=True)
    else:
        n4admin_password = admin_password

    print("\n  --- Game Settings ---\n")
    game_mode_name, game_mode_class = prompt_choice("Game Mode:", GAME_MODES)
    max_players = prompt("Max Players", default=8)
    nb_terro = prompt("Terrorist Count", default=30)
    round_time = prompt("Round Time (seconds)", default=300)
    between_round_time = prompt("Between Round Time (seconds)", default=45)
    bomb_time = prompt("Bomb Time (seconds)", default=300)
    rounds_per_match = prompt("Rounds Per Match", default=10)
    diff_level = prompt("Difficulty (1=Easy, 2=Normal, 3=Hard)", default=2)
    friendly_fire = prompt_yn("Friendly Fire?", default="y")
    force_first_person = prompt_yn("Force First Person Weapons?", default="y")
    rotate_map = prompt_yn("Map Rotation?", default="y")

    print("\n  --- Map Selection ---\n")
    print("  Available maps:")
    for i, m in enumerate(AVAILABLE_MAPS):
        print(f"    {m}", end="")
        if (i + 1) % 5 == 0:
            print()
    print("\n")
    maps = prompt("Maps (comma-separated)", default=DEFAULT_MAPS)

    print("\n  --- Network ---\n")
    public_ip = prompt("Public IP or domain name", required=True)
    server_beacon_port = prompt("Server Beacon Port", default=8777)
    rvsdash_port = prompt("RVSDash Dashboard Port", default=2003)

    print("\n  --- Server Ident ---\n")
    server_ident = prompt("Server Ident (short unique ID for this server)", default="rvs1")

    print("\n  --- Site Branding ---\n")
    site_title = prompt("Site Title (browser tab)", default=server_name)
    site_heading = prompt("Site Heading (page header)", default=server_name)

    config = {
        "server_name": server_name,
        "motd": motd,
        "admin_password": admin_password,
        "n4admin_password": n4admin_password,
        "game_mode_name": game_mode_name,
        "game_mode_class": game_mode_class,
        "max_players": max_players,
        "nb_terro": nb_terro,
        "round_time": round_time,
        "between_round_time": between_round_time,
        "bomb_time": bomb_time,
        "rounds_per_match": rounds_per_match,
        "diff_level": diff_level,
        "friendly_fire": "True" if friendly_fire else "False",
        "force_first_person": "True" if force_first_person else "False",
        "rotate_map": "True" if rotate_map else "False",
        "maps": maps,
        "public_ip": public_ip,
        "server_beacon_port": server_beacon_port,
        "rvsdash_port": rvsdash_port,
        "server_ident": server_ident,
        "site_title": site_title,
        "site_heading": site_heading,
    }

    write_env(config)
    write_compose(config)
    write_caddyfile()

    print()
    print("=" * 60)
    print()
    print("  Configuration complete!")
    print()
    print(f"  Server:    {server_name}")
    print(f"  Mode:      {game_mode_name}")
    print(f"  Maps:      {maps}")
    print(f"  Dashboard: http://{public_ip}:{rvsdash_port}/")
    print(f"  Downloads: http://{public_ip}/")
    print()
    print("  To start your server:")
    print()
    print("    docker compose pull")
    print("    docker compose up -d")
    print()
    print("  To reconfigure, run setup.py again, then:")
    print()
    print("    docker compose down")
    print("    docker compose up -d")
    print()
    print("=" * 60)
    print()


if __name__ == "__main__":
    main()